/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorInventario;
import java.io.IOException;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import modelo.Ingrediente;

/**
 *
 * @author maiam
 */
public class FrmInventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInventario.class.getName());
    
    private final ControladorInventario _controladorInventario;
    private String nombreSeleccionado;
    
    /**
     * Creates new form FrmInventario
     * @throws java.io.IOException
     */
    public FrmInventario() throws IOException {
        initComponents();
        _controladorInventario = new ControladorInventario();
        cargarTablaInventario();
    }
    
    private void cargarTablaInventario() {
        DefaultTableModel modelo = 
                (DefaultTableModel) tablaInventario.getModel();
        modelo.setRowCount(0);
        
        
        ArrayList<Ingrediente> listaIng = _controladorInventario.obtenerIngredientes();
        
        for (Ingrediente ing : listaIng) {
            String estado = ing.estaPorAgortarse() ? "Por agotarse!" : "OK";
            Object[] fila = {
                ing.getNombre(),ing.getUnidad(),ing.getStock(),ing.getStockMinimo(),estado
            };
            modelo.addRow(fila);
        }
        
    }
    
    private void limpiarCampos() {
        txtNombre.setText("");
        txtUnidad.setText("");
        txtStock.setText("");
        txtStockMinimo.setText("");
        nombreSeleccionado = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        lblUnidad = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblStockMinimo = new javax.swing.JLabel();
        txtStockMinimo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");

        lblUnidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnidad.setText("Unidad:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre: ");

        lblStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStock.setText("Stock:");

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar Ingrediente");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setText("Editar Ingrediente");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar ingrediente");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Unidad", "Stock", "Stock minimo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInventario);

        jLabel1.setBackground(new java.awt.Color(255, 102, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INVENTARIO-INGREDIENTES");
        jLabel1.setOpaque(true);

        lblStockMinimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStockMinimo.setText("Stock minimo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStockMinimo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblUnidad)
                            .addComponent(lblStock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidad)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStockMinimo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStockMinimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioMouseClicked
        int fila = tablaInventario.getSelectedRow();
        if (fila == -1) {
        }
        
        DefaultTableModel modelo = (DefaultTableModel)
                tablaInventario.getModel();
        
        String nombre = (String) modelo.getValueAt(fila, 0);
        String unidad = (String) modelo.getValueAt(fila, 1);
        Double stock = (Double) modelo.getValueAt(fila, 2);
        Double stockMinimo = (Double) modelo.getValueAt(fila, 3);
        
        txtNombre.setText(nombre);
        txtUnidad.setText(unidad);
        txtStock.setText(String.valueOf(stock));
        txtStockMinimo.setText(String.valueOf(stockMinimo));
        
        nombreSeleccionado = nombre;
        
    }//GEN-LAST:event_tablaInventarioMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txtNombre.getText().trim();
        String unidad = txtUnidad.getText().trim();
        String textoStock = txtStock.getText().trim();
        String textoStockMinimo = txtStockMinimo.getText().trim();
        
        if (textoStock.isEmpty() || textoStockMinimo.isEmpty()) {
            showMessageDialog(this, "Completa stock y stock minimo");
            return;
        }
        
        
        try {
            double stock = Double.parseDouble(textoStock);
            double stockMinimo = Double.parseDouble(textoStockMinimo);
            
            String resultado = _controladorInventario.registrarIngredientes(nombre, unidad, stock, stockMinimo);
            showMessageDialog(this, resultado);
            
            if (resultado.startsWith("EXITO")) {
                cargarTablaInventario();
                limpiarCampos();
            }
            
        } catch (NumberFormatException e) {
            showMessageDialog(this, "Stock y stock minimo deben ser numeros.");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (nombreSeleccionado == null) {
            showMessageDialog(this, "Primero haz clic en un ingrediente de la tabla.");
            return;
        }
        
        String nuevoNombre = txtNombre.getText().trim();
        String nuevaUnidad = txtUnidad.getText().trim();
        String textoStock = txtStock.getText().trim();
        String textoStockMinimo = txtStockMinimo.getText().trim();
        
        if (textoStock.isEmpty() || textoStockMinimo.isEmpty()) {
            showMessageDialog(this, "Completa stock y stock minimo.");
            return;
        }
        
        try {
            double nuevoStock = Double.parseDouble(textoStock);
            double nuevoStockMinimo = Double.parseDouble(textoStockMinimo);
            
            String resultado = _controladorInventario.editarIngrediente(
                    nombreSeleccionado, nuevoNombre, nuevaUnidad, nuevoStock, nuevoStockMinimo);
            showMessageDialog(this, resultado);
            
            if (resultado.startsWith("EXITO")) {
                cargarTablaInventario();
                limpiarCampos();
            }
            
        } catch (NumberFormatException e) {
            showMessageDialog(this, "Stock y stock minimo deben ser numeros.");
        }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (nombreSeleccionado == null) {
            showMessageDialog(this, "Primero haz clic en un ingrediente de la tabla.");
            return;
        }
        
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar \"" + nombreSeleccionado + "\"?",
                "Confirmar eliminacion",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }
        
        String resultado = _controladorInventario.eliminarIngrediente(nombreSeleccionado);
        showMessageDialog(this, resultado);
        
        if (resultado.startsWith("EXITO")) {
            cargarTablaInventario();
            limpiarCampos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FrmInventario().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(FrmInventario.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblStockMinimo;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStockMinimo;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
